services:
  mongo:
    image: mongo:6.0
    container_name: mongodb_container
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    restart: always

  service_a:
    build:
      context: ./service_a
    volumes:
      - /tmp:/tmp
    ports:
      - "8000:8000"  
    restart: always

  service_b:
    build:
      context: ./service_b
    volumes:
      - /tmp:/tmp
    ports:
      - "8001:8001"  
    restart: always

  service-ui:
    build:
      context: ./service-ui
    ports:
      - "3000:80"
    restart: always

volumes:
  mongo_data:
