version: '3.8'

services:
  # Service MongoDB
  mongo:
    image: mongo:6.0     # Utilise l'image officielle de MongoDB
    container_name: mongodb_container
    ports:
      - "27017:27017"   # Expose MongoDB sur le port 27017 (modifiable si nécessaire)
    volumes:
      - mongo_data:/data/db # Volume pour persister les données
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin       # Définir un utilisateur admin
      MONGO_INITDB_ROOT_PASSWORD: password    # Définir un mot de passe admin

  # Service B
  service_b:
    build:
      context: ./service_b
    volumes:
      - /tmp:/tmp  # Share /tmp for the Unix Domain Socket
    restart: always

  # Service A
  service_a:
    build:
      context: ./service_a
    volumes:
      - /tmp:/tmp  # Share /tmp for the Unix Domain Socket
    ports:
      - "8000:8000"  # Expose service_a's port to access it from outside
    depends_on:
      - service_b
    restart: always

volumes:
  mongo_data:
    driver: local  # Persistance locale
