version: '3.8'

services:
  # Service MongoDB
  mongo:
    image: mongo:6.0      # Utilise l'image officielle de MongoDB
    container_name: mongodb_container
    ports:
      - "27017:27017"     # Expose MongoDB sur le port 27017
    volumes:
      - mongo_data:/data/db  # Volume pour persister les données MongoDB
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin       # Nom d'utilisateur pour MongoDB
      MONGO_INITDB_ROOT_PASSWORD: password    # Mot de passe pour MongoDB
    restart: always        # Redémarrer automatiquement MongoDB en cas d'erreur

  # Service B
  service_b:
    build:
      context: ./service_b
    volumes:
      - /tmp:/tmp          # Partage du répertoire /tmp pour le Domain Socket
    restart: always        # Redémarrer automatiquement Service B en cas d'erreur

  # Service A
  service_a:
    build:
      context: ./service_a
    volumes:
      - /tmp:/tmp          # Partage du répertoire /tmp pour le Domain Socket
    ports:
      - "8000:8000"        # Expose le service A sur le port 8000
    depends_on:
      - service_b          # Assure que Service B est lancé avant Service A
      - mongo              # Assure que MongoDB est lancé avant Service A
    environment:
      MONGO_URI: mongodb://admin:password@mongo:27017  # URI de connexion à MongoDB
    restart: always        # Redémarrer automatiquement Service A en cas d'erreur

volumes:
  mongo_data:

